INSERT INTO zipcodes (region, commune, zipcode, city)
VALUES ('Nordjylland', 'Morsø Kommune', 7900, 'Nykøbing M'),
       ('Nordjylland', 'Morsø Kommune', 7950, 'Erslev'),
       ('Nordjylland', 'Morsø Kommune', 7960, 'Karby'),
       ('Nordjylland', 'Morsø Kommune', 7970, 'Redsted M'),
       ('Nordjylland', 'Morsø Kommune', 7980, 'Vils'),
       ('Nordjylland', 'Morsø Kommune', 7990, 'Øster Assels'),
       ('Nordjylland', 'Thisted Kommune', 7700, 'Thisted'),
       ('Nordjylland', 'Thisted Kommune', 7730, 'Hanstholm'),
       ('Nordjylland', 'Thisted Kommune', 7741, 'Frøstrup'),
       ('Nordjylland', 'Thisted Kommune', 7742, 'Vesløs'),
       ('Nordjylland', 'Thisted Kommune', 7752, 'Snedsted'),
       ('Nordjylland', 'Thisted Kommune', 7755, 'Bedsted Thy'),
       ('Nordjylland', 'Thisted Kommune', 7760, 'Hurup Thy'),
       ('Nordjylland', 'Thisted Kommune', 7770, 'Vestervig'),
       ('Nordjylland', 'Brønderslev Kommune', 9320, 'Hjallerup'),
       ('Nordjylland', 'Brønderslev Kommune', 9330, 'Dronninglund'),
       ('Nordjylland', 'Brønderslev Kommune', 9340, 'Asaa'),
       ('Nordjylland', 'Brønderslev Kommune', 9352, 'Dybvad'),
       ('Nordjylland', 'Brønderslev Kommune', 9370, 'Hals'),
       ('Nordjylland', 'Brønderslev Kommune', 9382, 'Tylstrup'),
       ('Nordjylland', 'Brønderslev Kommune', 9440, 'Aabybro'),
       ('Nordjylland', 'Brønderslev Kommune', 9480, 'Løkken'),
       ('Nordjylland', 'Brønderslev Kommune', 9700, 'Brønderslev'),
       ('Nordjylland', 'Brønderslev Kommune', 9740, 'Jerslev J'),
       ('Nordjylland', 'Brønderslev Kommune', 9750, 'Østervrå'),
       ('Nordjylland', 'Brønderslev Kommune', 9760, 'Vrå'),
       ('Nordjylland', 'Frederikshavn Kommune', 9300, 'Sæby'),
       ('Nordjylland', 'Frederikshavn Kommune', 9330, 'Dronninglund'),
       ('Nordjylland', 'Frederikshavn Kommune', 9340, 'Asaa'),
       ('Nordjylland', 'Frederikshavn Kommune', 9352, 'Dybvad'),
       ('Nordjylland', 'Frederikshavn Kommune', 9750, 'Østervrå'),
       ('Nordjylland', 'Frederikshavn Kommune', 9830, 'Tårs'),
       ('Nordjylland', 'Frederikshavn Kommune', 9870, 'Sindal'),
       ('Nordjylland', 'Frederikshavn Kommune', 9881, 'Bindslev'),
       ('Nordjylland', 'Frederikshavn Kommune', 9900, 'Frederikshavn'),
       ('Nordjylland', 'Frederikshavn Kommune', 9970, 'Strandby'),
       ('Nordjylland', 'Frederikshavn Kommune', 9981, 'Jerup'),
       ('Nordjylland', 'Frederikshavn Kommune', 9982, 'Ålbæk'),
       ('Nordjylland', 'Frederikshavn Kommune', 9990, 'Skagen'),
       ('Nordjylland', 'Vesthimmerlands Kommune', 9240, 'Nibe'),
       ('Nordjylland', 'Vesthimmerlands Kommune', 9541, 'Suldrup'),
       ('Nordjylland', 'Vesthimmerlands Kommune', 9600, 'Aars'),
       ('Nordjylland', 'Vesthimmerlands Kommune', 9610, 'Nørager'),
       ('Nordjylland', 'Vesthimmerlands Kommune', 9620, 'Aalestrup'),
       ('Nordjylland', 'Vesthimmerlands Kommune', 9631, 'Gedsted'),
       ('Nordjylland', 'Vesthimmerlands Kommune', 9640, 'Farsø'),
       ('Nordjylland', 'Vesthimmerlands Kommune', 9670, 'Løgstør'),
       ('Nordjylland', 'Vesthimmerlands Kommune', 9681, 'Ranum'),
       ('Nordjylland', 'Læsø Kommune', 9940, 'Læsø'),
       ('Nordjylland', 'Rebild Kommune', 9230, 'Svenstrup J'),
       ('Nordjylland', 'Rebild Kommune', 9240, 'Nibe'),
       ('Nordjylland', 'Rebild Kommune', 9260, 'Gistrup'),
       ('Nordjylland', 'Rebild Kommune', 9293, 'Kongerslev'),
       ('Nordjylland', 'Rebild Kommune', 9500, 'Hobro'),
       ('Nordjylland', 'Rebild Kommune', 9510, 'Arden'),
       ('Nordjylland', 'Rebild Kommune', 9520, 'Skørping'),
       ('Nordjylland', 'Rebild Kommune', 9530, 'Støvring'),
       ('Nordjylland', 'Rebild Kommune', 9541, 'Suldrup'),
       ('Nordjylland', 'Rebild Kommune', 9560, 'Hadsund'),
       ('Nordjylland', 'Rebild Kommune', 9574, 'Bælum'),
       ('Nordjylland', 'Rebild Kommune', 9575, 'Terndrup'),
       ('Nordjylland', 'Rebild Kommune', 9600, 'Aars'),
       ('Nordjylland', 'Rebild Kommune', 9610, 'Nørager'),
       ('Nordjylland', 'Rebild Kommune', 9620, 'Aalestrup'),
       ('Nordjylland', 'Mariagerfjord Kommune', 8970, 'Havndal'),
       ('Nordjylland', 'Mariagerfjord Kommune', 8990, 'Fårup'),
       ('Nordjylland', 'Mariagerfjord Kommune', 9500, 'Hobro'),
       ('Nordjylland', 'Mariagerfjord Kommune', 9510, 'Arden'),
       ('Nordjylland', 'Mariagerfjord Kommune', 9550, 'Mariager'),
       ('Nordjylland', 'Mariagerfjord Kommune', 9560, 'Hadsund'),
       ('Nordjylland', 'Mariagerfjord Kommune', 9620, 'Aalestrup'),
       ('Nordjylland', 'Mariagerfjord Kommune', 9632, 'Møldrup'),
       ('Nordjylland', 'Jammerbugt Kommune', 9381, 'Sulsted'),
       ('Nordjylland', 'Jammerbugt Kommune', 9382, 'Tylstrup'),
       ('Nordjylland', 'Jammerbugt Kommune', 9430, 'Vadum'),
       ('Nordjylland', 'Jammerbugt Kommune', 9440, 'Aabybro'),
       ('Nordjylland', 'Jammerbugt Kommune', 9460, 'Brovst'),
       ('Nordjylland', 'Jammerbugt Kommune', 9480, 'Løkken'),
       ('Nordjylland', 'Jammerbugt Kommune', 9490, 'Pandrup'),
       ('Nordjylland', 'Jammerbugt Kommune', 9492, 'Blokhus'),
       ('Nordjylland', 'Jammerbugt Kommune', 9493, 'Saltum'),
       ('Nordjylland', 'Jammerbugt Kommune', 9670, 'Løgstør'),
       ('Nordjylland', 'Jammerbugt Kommune', 9690, 'Fjerritslev'),
       ('Nordjylland', 'Jammerbugt Kommune', 9700, 'Brønderslev'),
       ('Nordjylland', 'Aalborg Kommune', 9000, 'Aalborg'),
       ('Nordjylland', 'Aalborg Kommune', 9200, 'Aalborg SV'),
       ('Nordjylland', 'Aalborg Kommune', 9210, 'Aalborg SØ'),
       ('Nordjylland', 'Aalborg Kommune', 9220, 'Aalborg Øst'),
       ('Nordjylland', 'Aalborg Kommune', 9230, 'Svenstrup J'),
       ('Nordjylland', 'Aalborg Kommune', 9240, 'Nibe'),
       ('Nordjylland', 'Aalborg Kommune', 9260, 'Gistrup'),
       ('Nordjylland', 'Aalborg Kommune', 9270, 'Klarup'),
       ('Nordjylland', 'Aalborg Kommune', 9280, 'Storvorde'),
       ('Nordjylland', 'Aalborg Kommune', 9293, 'Kongerslev'),
       ('Nordjylland', 'Aalborg Kommune', 9310, 'Vodskov'),
       ('Nordjylland', 'Aalborg Kommune', 9320, 'Hjallerup'),
       ('Nordjylland', 'Aalborg Kommune', 9362, 'Gandrup'),
       ('Nordjylland', 'Aalborg Kommune', 9370, 'Hals'),
       ('Nordjylland', 'Aalborg Kommune', 9380, 'Vestbjerg'),
       ('Nordjylland', 'Aalborg Kommune', 9381, 'Sulsted'),
       ('Nordjylland', 'Aalborg Kommune', 9382, 'Tylstrup'),
       ('Nordjylland', 'Aalborg Kommune', 9400, 'Nørresundby'),
       ('Nordjylland', 'Aalborg Kommune', 9430, 'Vadum'),
       ('Nordjylland', 'Aalborg Kommune', 9440, 'Aabybro'),
       ('Nordjylland', 'Aalborg Kommune', 9530, 'Støvring'),
       ('Nordjylland', 'Hjørring Kommune', 9480, 'Løkken'),
       ('Nordjylland', 'Hjørring Kommune', 9740, 'Jerslev J'),
       ('Nordjylland', 'Hjørring Kommune', 9750, 'Østervrå'),
       ('Nordjylland', 'Hjørring Kommune', 9760, 'Vrå'),
       ('Nordjylland', 'Hjørring Kommune', 9800, 'Hjørring'),
       ('Nordjylland', 'Hjørring Kommune', 9830, 'Tårs'),
       ('Nordjylland', 'Hjørring Kommune', 9850, 'Hirtshals'),
       ('Nordjylland', 'Hjørring Kommune', 9870, 'Sindal'),
       ('Nordjylland', 'Hjørring Kommune', 9881, 'Bindslev'),
       ('Nordjylland', 'Hjørring Kommune', 9900, 'Frederikshavn'),
       ('Nordjylland', 'Hjørring Kommune', 9982, 'Ålbæk'),
       ('Midtjylland', 'Horsens Kommune', 8654, 'Bryrup'),
       ('Midtjylland', 'Horsens Kommune', 8660, 'Skanderborg'),
       ('Midtjylland', 'Horsens Kommune', 8680, 'Ry'),
       ('Midtjylland', 'Horsens Kommune', 8700, 'Horsens'),
       ('Midtjylland', 'Horsens Kommune', 8732, 'Hovedgård'),
       ('Midtjylland', 'Horsens Kommune', 8740, 'Brædstrup'),
       ('Midtjylland', 'Horsens Kommune', 8751, 'Gedved'),
       ('Midtjylland', 'Horsens Kommune', 8752, 'Østbirk'),
       ('Midtjylland', 'Horsens Kommune', 8762, 'Flemming'),
       ('Midtjylland', 'Horsens Kommune', 8765, 'Klovborg'),
       ('Midtjylland', 'Horsens Kommune', 8781, 'Stenderup'),
       ('Midtjylland', 'Horsens Kommune', 8783, 'Hornsyld'),
       ('Midtjylland', 'Herning Kommune', 6933, 'Kibæk'),
       ('Midtjylland', 'Herning Kommune', 6973, 'Ørnhøj'),
       ('Midtjylland', 'Herning Kommune', 6990, 'Ulfborg'),
       ('Midtjylland', 'Herning Kommune', 7260, 'Sønder Omme'),
       ('Midtjylland', 'Herning Kommune', 7270, 'Stakroge'),
       ('Midtjylland', 'Herning Kommune', 7280, 'Sønder Felding'),
       ('Midtjylland', 'Herning Kommune', 7330, 'Brande'),
       ('Midtjylland', 'Herning Kommune', 7400, 'Herning'),
       ('Midtjylland', 'Herning Kommune', 7451, 'Sunds'),
       ('Midtjylland', 'Herning Kommune', 7470, 'Karup J'),
       ('Midtjylland', 'Herning Kommune', 7480, 'Vildbjerg'),
       ('Midtjylland', 'Herning Kommune', 7490, 'Aulum'),
       ('Midtjylland', 'Herning Kommune', 7500, 'Holstebro'),
       ('Midtjylland', 'Herning Kommune', 7540, 'Haderup'),
       ('Midtjylland', 'Herning Kommune', 7550, 'Sørvad'),
       ('Midtjylland', 'Herning Kommune', 7830, 'Vinderup'),
       ('Midtjylland', 'Holstebro Kommune', 6990, 'Ulfborg'),
       ('Midtjylland', 'Holstebro Kommune', 7500, 'Holstebro'),
       ('Midtjylland', 'Holstebro Kommune', 7540, 'Haderup'),
       ('Midtjylland', 'Holstebro Kommune', 7560, 'Hjerm'),
       ('Midtjylland', 'Holstebro Kommune', 7570, 'Vemb'),
       ('Midtjylland', 'Holstebro Kommune', 7600, 'Struer'),
       ('Midtjylland', 'Holstebro Kommune', 7800, 'Skive'),
       ('Midtjylland', 'Holstebro Kommune', 7830, 'Vinderup'),
       ('Midtjylland', 'Lemvig Kommune', 6990, 'Ulfborg'),
       ('Midtjylland', 'Lemvig Kommune', 7570, 'Vemb'),
       ('Midtjylland', 'Lemvig Kommune', 7600, 'Struer'),
       ('Midtjylland', 'Lemvig Kommune', 7620, 'Lemvig'),
       ('Midtjylland', 'Lemvig Kommune', 7650, 'Bøvlingbjerg'),
       ('Midtjylland', 'Lemvig Kommune', 7660, 'Bækmarksbro'),
       ('Midtjylland', 'Lemvig Kommune', 7673, 'Harboøre'),
       ('Midtjylland', 'Lemvig Kommune', 7680, 'Thyborøn'),
       ('Midtjylland', 'Struer Kommune', 7500, 'Holstebro'),
       ('Midtjylland', 'Struer Kommune', 7560, 'Hjerm'),
       ('Midtjylland', 'Struer Kommune', 7600, 'Struer'),
       ('Midtjylland', 'Struer Kommune', 7660, 'Bækmarksbro'),
       ('Midtjylland', 'Struer Kommune', 7760, 'Hurup Thy'),
       ('Midtjylland', 'Struer Kommune', 7790, 'Thyholm'),
       ('Midtjylland', 'Struer Kommune', 7830, 'Vinderup'),
       ('Midtjylland', 'Syddjurs Kommune', 8400, 'Ebeltoft'),
       ('Midtjylland', 'Syddjurs Kommune', 8410, 'Rønde'),
       ('Midtjylland', 'Syddjurs Kommune', 8420, 'Knebel'),
       ('Midtjylland', 'Syddjurs Kommune', 8444, 'Balle'),
       ('Midtjylland', 'Syddjurs Kommune', 8543, 'Hornslet'),
       ('Midtjylland', 'Syddjurs Kommune', 8544, 'Mørke'),
       ('Midtjylland', 'Syddjurs Kommune', 8550, 'Ryomgård'),
       ('Midtjylland', 'Syddjurs Kommune', 8560, 'Kolind'),
       ('Midtjylland', 'Syddjurs Kommune', 8570, 'Trustrup'),
       ('Midtjylland', 'Syddjurs Kommune', 8581, 'Nimtofte'),
       ('Midtjylland', 'Syddjurs Kommune', 8963, 'Auning'),
       ('Midtjylland', 'Norddjurs Kommune', 8444, 'Balle'),
       ('Midtjylland', 'Norddjurs Kommune', 8500, 'Grenaa'),
       ('Midtjylland', 'Norddjurs Kommune', 8550, 'Ryomgård'),
       ('Midtjylland', 'Norddjurs Kommune', 8560, 'Kolind'),
       ('Midtjylland', 'Norddjurs Kommune', 8570, 'Trustrup'),
       ('Midtjylland', 'Norddjurs Kommune', 8581, 'Nimtofte'),
       ('Midtjylland', 'Norddjurs Kommune', 8585, 'Glesborg'),
       ('Midtjylland', 'Norddjurs Kommune', 8586, 'Ørum Djurs'),
       ('Midtjylland', 'Norddjurs Kommune', 8592, 'Anholt'),
       ('Midtjylland', 'Norddjurs Kommune', 8950, 'Ørsted'),
       ('Midtjylland', 'Norddjurs Kommune', 8961, 'Allingåbro'),
       ('Midtjylland', 'Norddjurs Kommune', 8963, 'Auning'),
       ('Midtjylland', 'Favrskov Kommune', 8370, 'Hadsten'),
       ('Midtjylland', 'Favrskov Kommune', 8380, 'Trige'),
       ('Midtjylland', 'Favrskov Kommune', 8382, 'Hinnerup'),
       ('Midtjylland', 'Favrskov Kommune', 8450, 'Hammel'),
       ('Midtjylland', 'Favrskov Kommune', 8471, 'Sabro'),
       ('Midtjylland', 'Favrskov Kommune', 8472, 'Sporup'),
       ('Midtjylland', 'Favrskov Kommune', 8641, 'Sorring'),
       ('Midtjylland', 'Favrskov Kommune', 8850, 'Bjerringbro'),
       ('Midtjylland', 'Favrskov Kommune', 8860, 'Ulstrup'),
       ('Midtjylland', 'Favrskov Kommune', 8870, 'Langå'),
       ('Midtjylland', 'Favrskov Kommune', 8881, 'Thorsø'),
       ('Midtjylland', 'Favrskov Kommune', 8882, 'Fårvang'),
       ('Midtjylland', 'Favrskov Kommune', 8940, 'Randers SV'),
       ('Midtjylland', 'Favrskov Kommune', 8960, 'Randers SØ'),
       ('Midtjylland', 'Odder Kommune', 8300, 'Odder'),
       ('Midtjylland', 'Odder Kommune', 8340, 'Malling'),
       ('Midtjylland', 'Odder Kommune', 8350, 'Hundslund'),
       ('Midtjylland', 'Odder Kommune', 8660, 'Skanderborg'),
       ('Midtjylland', 'Randers Kommune', 8860, 'Ulstrup'),
       ('Midtjylland', 'Randers Kommune', 8870, 'Langå'),
       ('Midtjylland', 'Randers Kommune', 8900, 'Randers C'),
       ('Midtjylland', 'Randers Kommune', 8920, 'Randers NV'),
       ('Midtjylland', 'Randers Kommune', 8930, 'Randers NØ'),
       ('Midtjylland', 'Randers Kommune', 8940, 'Randers SV'),
       ('Midtjylland', 'Randers Kommune', 8960, 'Randers SØ'),
       ('Midtjylland', 'Randers Kommune', 8970, 'Havndal'),
       ('Midtjylland', 'Randers Kommune', 8981, 'Spentrup'),
       ('Midtjylland', 'Randers Kommune', 8983, 'Gjerlev J'),
       ('Midtjylland', 'Randers Kommune', 8990, 'Fårup'),
       ('Midtjylland', 'Randers Kommune', 9550, 'Mariager'),
       ('Midtjylland', 'Silkeborg Kommune', 7362, 'Hampen'),
       ('Midtjylland', 'Silkeborg Kommune', 7441, 'Bording'),
       ('Midtjylland', 'Silkeborg Kommune', 7442, 'Engesvang'),
       ('Midtjylland', 'Silkeborg Kommune', 7470, 'Karup J'),
       ('Midtjylland', 'Silkeborg Kommune', 8450, 'Hammel'),
       ('Midtjylland', 'Silkeborg Kommune', 8472, 'Sporup'),
       ('Midtjylland', 'Silkeborg Kommune', 8600, 'Silkeborg'),
       ('Midtjylland', 'Silkeborg Kommune', 8620, 'Kjellerup'),
       ('Midtjylland', 'Silkeborg Kommune', 8632, 'Lemming'),
       ('Midtjylland', 'Silkeborg Kommune', 8641, 'Sorring'),
       ('Midtjylland', 'Silkeborg Kommune', 8643, 'Ans By'),
       ('Midtjylland', 'Silkeborg Kommune', 8653, 'Them'),
       ('Midtjylland', 'Silkeborg Kommune', 8654, 'Bryrup'),
       ('Midtjylland', 'Silkeborg Kommune', 8680, 'Ry'),
       ('Midtjylland', 'Silkeborg Kommune', 8740, 'Brædstrup'),
       ('Midtjylland', 'Silkeborg Kommune', 8800, 'Viborg'),
       ('Midtjylland', 'Silkeborg Kommune', 8840, 'Rødkærsbro'),
       ('Midtjylland', 'Silkeborg Kommune', 8881, 'Thorsø'),
       ('Midtjylland', 'Silkeborg Kommune', 8882, 'Fårvang'),
       ('Midtjylland', 'Silkeborg Kommune', 8883, 'Gjern'),
       ('Midtjylland', 'Samsø Kommune', 8305, 'Samsø'),
       ('Midtjylland', 'Skanderborg Kommune', 8362, 'Hørning'),
       ('Midtjylland', 'Skanderborg Kommune', 8464, 'Galten'),
       ('Midtjylland', 'Skanderborg Kommune', 8471, 'Sabro'),
       ('Midtjylland', 'Skanderborg Kommune', 8472, 'Sporup'),
       ('Midtjylland', 'Skanderborg Kommune', 8600, 'Silkeborg'),
       ('Midtjylland', 'Skanderborg Kommune', 8660, 'Skanderborg'),
       ('Midtjylland', 'Skanderborg Kommune', 8670, 'Låsby'),
       ('Midtjylland', 'Skanderborg Kommune', 8680, 'Ry'),
       ('Midtjylland', 'Skanderborg Kommune', 8751, 'Gedved'),
       ('Midtjylland', 'Aarhus Kommune', 8000, 'Aarhus C'),
       ('Midtjylland', 'Aarhus Kommune', 8200, 'Aarhus N'),
       ('Midtjylland', 'Aarhus Kommune', 8210, 'Aarhus V'),
       ('Midtjylland', 'Aarhus Kommune', 8220, 'Brabrand'),
       ('Midtjylland', 'Aarhus Kommune', 8230, 'Åbyhøj'),
       ('Midtjylland', 'Aarhus Kommune', 8240, 'Risskov'),
       ('Midtjylland', 'Aarhus Kommune', 8245, 'Risskov Ø'),
       ('Midtjylland', 'Aarhus Kommune', 8250, 'Egå'),
       ('Midtjylland', 'Aarhus Kommune', 8260, 'Viby J'),
       ('Midtjylland', 'Aarhus Kommune', 8270, 'Højbjerg'),
       ('Midtjylland', 'Aarhus Kommune', 8300, 'Odder'),
       ('Midtjylland', 'Aarhus Kommune', 8310, 'Tranbjerg J'),
       ('Midtjylland', 'Aarhus Kommune', 8320, 'Mårslet'),
       ('Midtjylland', 'Aarhus Kommune', 8330, 'Beder'),
       ('Midtjylland', 'Aarhus Kommune', 8340, 'Malling'),
       ('Midtjylland', 'Aarhus Kommune', 8355, 'Solbjerg'),
       ('Midtjylland', 'Aarhus Kommune', 8361, 'Hasselager'),
       ('Midtjylland', 'Aarhus Kommune', 8362, 'Hørning'),
       ('Midtjylland', 'Aarhus Kommune', 8380, 'Trige'),
       ('Midtjylland', 'Aarhus Kommune', 8381, 'Tilst'),
       ('Midtjylland', 'Aarhus Kommune', 8382, 'Hinnerup'),
       ('Midtjylland', 'Aarhus Kommune', 8462, 'Harlev J'),
       ('Midtjylland', 'Aarhus Kommune', 8464, 'Galten'),
       ('Midtjylland', 'Aarhus Kommune', 8471, 'Sabro'),
       ('Midtjylland', 'Aarhus Kommune', 8520, 'Lystrup'),
       ('Midtjylland', 'Aarhus Kommune', 8530, 'Hjortshøj'),
       ('Midtjylland', 'Aarhus Kommune', 8541, 'Skødstrup'),
       ('Midtjylland', 'Aarhus Kommune', 8543, 'Hornslet'),
       ('Midtjylland', 'Aarhus Kommune', 8660, 'Skanderborg'),
       ('Midtjylland', 'Ikast-Brande Kommune', 7160, 'Tørring'),
       ('Midtjylland', 'Ikast-Brande Kommune', 7330, 'Brande'),
       ('Midtjylland', 'Ikast-Brande Kommune', 7361, 'Ejstrupholm'),
       ('Midtjylland', 'Ikast-Brande Kommune', 7362, 'Hampen'),
       ('Midtjylland', 'Ikast-Brande Kommune', 7400, 'Herning'),
       ('Midtjylland', 'Ikast-Brande Kommune', 7430, 'Ikast'),
       ('Midtjylland', 'Ikast-Brande Kommune', 7441, 'Bording'),
       ('Midtjylland', 'Ikast-Brande Kommune', 7442, 'Engesvang'),
       ('Midtjylland', 'Ikast-Brande Kommune', 7451, 'Sunds'),
       ('Midtjylland', 'Ikast-Brande Kommune', 8600, 'Silkeborg'),
       ('Midtjylland', 'Ikast-Brande Kommune', 8654, 'Bryrup'),
       ('Midtjylland', 'Ikast-Brande Kommune', 8765, 'Klovborg'),
       ('Midtjylland', 'Ikast-Brande Kommune', 8766, 'Nørre Snede'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 6830, 'Nørre Nebel'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 6870, 'Ølgod'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 6880, 'Tarm'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 6893, 'Hemmet'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 6900, 'Skjern'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 6920, 'Videbæk'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 6933, 'Kibæk'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 6940, 'Lem St'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 6950, 'Ringkøbing'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 6960, 'Hvide Sande'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 6971, 'Spjald'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 6973, 'Ørnhøj'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 6980, 'Tim'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 6990, 'Ulfborg'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 7270, 'Stakroge'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 7280, 'Sønder Felding'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 7400, 'Herning'),
       ('Midtjylland', 'Ringkøbing-Skjern Kommune', 7480, 'Vildbjerg'),
       ('Midtjylland', 'Hedensted Kommune', 7100, 'Vejle'),
       ('Midtjylland', 'Hedensted Kommune', 7120, 'Vejle Øst'),
       ('Midtjylland', 'Hedensted Kommune', 7130, 'Juelsminde'),
       ('Midtjylland', 'Hedensted Kommune', 7140, 'Stouby'),
       ('Midtjylland', 'Hedensted Kommune', 7150, 'Barrit'),
       ('Midtjylland', 'Hedensted Kommune', 7160, 'Tørring'),
       ('Midtjylland', 'Hedensted Kommune', 7171, 'Uldum'),
       ('Midtjylland', 'Hedensted Kommune', 7323, 'Give'),
       ('Midtjylland', 'Hedensted Kommune', 8700, 'Horsens'),
       ('Midtjylland', 'Hedensted Kommune', 8721, 'Daugård'),
       ('Midtjylland', 'Hedensted Kommune', 8722, 'Hedensted'),
       ('Midtjylland', 'Hedensted Kommune', 8723, 'Løsning'),
       ('Midtjylland', 'Hedensted Kommune', 8762, 'Flemming'),
       ('Midtjylland', 'Hedensted Kommune', 8763, 'Rask Mølle'),
       ('Midtjylland', 'Hedensted Kommune', 8766, 'Nørre Snede'),
       ('Midtjylland', 'Hedensted Kommune', 8781, 'Stenderup'),
       ('Midtjylland', 'Hedensted Kommune', 8783, 'Hornsyld'),
       ('Midtjylland', 'Skive Kommune', 7800, 'Skive'),
       ('Midtjylland', 'Skive Kommune', 7830, 'Vinderup'),
       ('Midtjylland', 'Skive Kommune', 7840, 'Højslev'),
       ('Midtjylland', 'Skive Kommune', 7860, 'Spøttrup'),
       ('Midtjylland', 'Skive Kommune', 7870, 'Roslev'),
       ('Midtjylland', 'Skive Kommune', 7884, 'Fur'),
       ('Midtjylland', 'Viborg Kommune', 7470, 'Karup J'),
       ('Midtjylland', 'Viborg Kommune', 7540, 'Haderup'),
       ('Midtjylland', 'Viborg Kommune', 7800, 'Skive'),
       ('Midtjylland', 'Viborg Kommune', 7840, 'Højslev'),
       ('Midtjylland', 'Viborg Kommune', 7850, 'Stoholm Jyll'),
       ('Midtjylland', 'Viborg Kommune', 8620, 'Kjellerup'),
       ('Midtjylland', 'Viborg Kommune', 8643, 'Ans By'),
       ('Midtjylland', 'Viborg Kommune', 8800, 'Viborg'),
       ('Midtjylland', 'Viborg Kommune', 8830, 'Tjele'),
       ('Midtjylland', 'Viborg Kommune', 8831, 'Løgstrup'),
       ('Midtjylland', 'Viborg Kommune', 8832, 'Skals'),
       ('Midtjylland', 'Viborg Kommune', 8840, 'Rødkærsbro'),
       ('Midtjylland', 'Viborg Kommune', 8850, 'Bjerringbro'),
       ('Midtjylland', 'Viborg Kommune', 8860, 'Ulstrup'),
       ('Midtjylland', 'Viborg Kommune', 9500, 'Hobro'),
       ('Midtjylland', 'Viborg Kommune', 9620, 'Aalestrup'),
       ('Midtjylland', 'Viborg Kommune', 9631, 'Gedsted'),
       ('Midtjylland', 'Viborg Kommune', 9632, 'Møldrup'),
       ('Syddanmark', 'Middelfart Kommune', 5463, 'Harndrup'),
       ('Syddanmark', 'Middelfart Kommune', 5464, 'Brenderup Fyn'),
       ('Syddanmark', 'Middelfart Kommune', 5466, 'Asperup'),
       ('Syddanmark', 'Middelfart Kommune', 5500, 'Middelfart'),
       ('Syddanmark', 'Middelfart Kommune', 5560, 'Aarup'),
       ('Syddanmark', 'Middelfart Kommune', 5580, 'Nørre Aaby'),
       ('Syddanmark', 'Middelfart Kommune', 5591, 'Gelsted'),
       ('Syddanmark', 'Middelfart Kommune', 5592, 'Ejby'),
       ('Syddanmark', 'Assens Kommune', 5492, 'Vissenbjerg'),
       ('Syddanmark', 'Assens Kommune', 5560, 'Aarup'),
       ('Syddanmark', 'Assens Kommune', 5610, 'Assens'),
       ('Syddanmark', 'Assens Kommune', 5620, 'Glamsbjerg'),
       ('Syddanmark', 'Assens Kommune', 5631, 'Ebberup'),
       ('Syddanmark', 'Assens Kommune', 5642, 'Millinge'),
       ('Syddanmark', 'Assens Kommune', 5683, 'Haarby'),
       ('Syddanmark', 'Assens Kommune', 5690, 'Tommerup'),
       ('Syddanmark', 'Faaborg-Midtfyn Kommune', 5550, 'Langeskov'),
       ('Syddanmark', 'Faaborg-Midtfyn Kommune', 5600, 'Faaborg'),
       ('Syddanmark', 'Faaborg-Midtfyn Kommune', 5642, 'Millinge'),
       ('Syddanmark', 'Faaborg-Midtfyn Kommune', 5672, 'Broby'),
       ('Syddanmark', 'Faaborg-Midtfyn Kommune', 5750, 'Ringe'),
       ('Syddanmark', 'Faaborg-Midtfyn Kommune', 5762, 'Vester Skerninge'),
       ('Syddanmark', 'Faaborg-Midtfyn Kommune', 5771, 'Stenstrup'),
       ('Syddanmark', 'Faaborg-Midtfyn Kommune', 5772, 'Kværndrup'),
       ('Syddanmark', 'Faaborg-Midtfyn Kommune', 5792, 'Årslev'),
       ('Syddanmark', 'Faaborg-Midtfyn Kommune', 5853, 'Ørbæk'),
       ('Syddanmark', 'Faaborg-Midtfyn Kommune', 5854, 'Gislev'),
       ('Syddanmark', 'Faaborg-Midtfyn Kommune', 5856, 'Ryslinge'),
       ('Syddanmark', 'Faaborg-Midtfyn Kommune', 5863, 'Ferritslev Fyn'),
       ('Syddanmark', 'Kerteminde Kommune', 5290, 'Marslev'),
       ('Syddanmark', 'Kerteminde Kommune', 5300, 'Kerteminde'),
       ('Syddanmark', 'Kerteminde Kommune', 5330, 'Munkebo'),
       ('Syddanmark', 'Kerteminde Kommune', 5350, 'Rynkeby'),
       ('Syddanmark', 'Kerteminde Kommune', 5370, 'Mesinge'),
       ('Syddanmark', 'Kerteminde Kommune', 5380, 'Dalby'),
       ('Syddanmark', 'Kerteminde Kommune', 5390, 'Martofte'),
       ('Syddanmark', 'Kerteminde Kommune', 5540, 'Ullerslev'),
       ('Syddanmark', 'Kerteminde Kommune', 5550, 'Langeskov'),
       ('Syddanmark', 'Kerteminde Kommune', 5863, 'Ferritslev Fyn'),
       ('Syddanmark', 'Nyborg Kommune', 5540, 'Ullerslev'),
       ('Syddanmark', 'Nyborg Kommune', 5550, 'Langeskov'),
       ('Syddanmark', 'Nyborg Kommune', 5800, 'Nyborg'),
       ('Syddanmark', 'Nyborg Kommune', 5853, 'Ørbæk'),
       ('Syddanmark', 'Nyborg Kommune', 5871, 'Frørup'),
       ('Syddanmark', 'Nyborg Kommune', 5874, 'Hesselager'),
       ('Syddanmark', 'Odense Kommune', 5000, 'Odense C'),
       ('Syddanmark', 'Odense Kommune', 5200, 'Odense V'),
       ('Syddanmark', 'Odense Kommune', 5210, 'Odense NV'),
       ('Syddanmark', 'Odense Kommune', 5220, 'Odense SØ'),
       ('Syddanmark', 'Odense Kommune', 5230, 'Odense M'),
       ('Syddanmark', 'Odense Kommune', 5240, 'Odense NØ'),
       ('Syddanmark', 'Odense Kommune', 5250, 'Odense SV'),
       ('Syddanmark', 'Odense Kommune', 5260, 'Odense S'),
       ('Syddanmark', 'Odense Kommune', 5270, 'Odense N'),
       ('Syddanmark', 'Odense Kommune', 5320, 'Agedrup'),
       ('Syddanmark', 'Odense Kommune', 5330, 'Munkebo'),
       ('Syddanmark', 'Odense Kommune', 5491, 'Blommenslyst'),
       ('Syddanmark', 'Odense Kommune', 5492, 'Vissenbjerg'),
       ('Syddanmark', 'Svendborg Kommune', 5700, 'Svendborg'),
       ('Syddanmark', 'Svendborg Kommune', 5762, 'Vester Skerninge'),
       ('Syddanmark', 'Svendborg Kommune', 5771, 'Stenstrup'),
       ('Syddanmark', 'Svendborg Kommune', 5772, 'Kværndrup'),
       ('Syddanmark', 'Svendborg Kommune', 5854, 'Gislev'),
       ('Syddanmark', 'Svendborg Kommune', 5874, 'Hesselager'),
       ('Syddanmark', 'Svendborg Kommune', 5881, 'Skårup Fyn'),
       ('Syddanmark', 'Svendborg Kommune', 5882, 'Vejstrup'),
       ('Syddanmark', 'Svendborg Kommune', 5883, 'Oure'),
       ('Syddanmark', 'Svendborg Kommune', 5884, 'Gudme'),
       ('Syddanmark', 'Svendborg Kommune', 5892, 'Gudbjerg Sydfyn'),
       ('Syddanmark', 'Nordfyns Kommune', 5270, 'Odense N'),
       ('Syddanmark', 'Nordfyns Kommune', 5400, 'Bogense'),
       ('Syddanmark', 'Nordfyns Kommune', 5450, 'Otterup'),
       ('Syddanmark', 'Nordfyns Kommune', 5462, 'Morud'),
       ('Syddanmark', 'Nordfyns Kommune', 5471, 'Søndersø'),
       ('Syddanmark', 'Nordfyns Kommune', 5474, 'Veflinge'),
       ('Syddanmark', 'Nordfyns Kommune', 5485, 'Skamby'),
       ('Syddanmark', 'Nordfyns Kommune', 5491, 'Blommenslyst'),
       ('Syddanmark', 'Nordfyns Kommune', 5492, 'Vissenbjerg'),
       ('Syddanmark', 'Nordfyns Kommune', 5560, 'Aarup'),
       ('Syddanmark', 'Langeland Kommune', 5900, 'Rudkøbing'),
       ('Syddanmark', 'Langeland Kommune', 5932, 'Humble'),
       ('Syddanmark', 'Langeland Kommune', 5935, 'Bagenkop'),
       ('Syddanmark', 'Langeland Kommune', 5953, 'Tranekær'),
       ('Syddanmark', 'Ærø Kommune', 5960, 'Marstal'),
       ('Syddanmark', 'Ærø Kommune', 5970, 'Ærøskøbing'),
       ('Syddanmark', 'Ærø Kommune', 5985, 'Søby Ærø'),
       ('Syddanmark', 'Haderslev Kommune', 6070, 'Christiansfeld'),
       ('Syddanmark', 'Haderslev Kommune', 6094, 'Hejls'),
       ('Syddanmark', 'Haderslev Kommune', 6100, 'Haderslev'),
       ('Syddanmark', 'Haderslev Kommune', 6500, 'Vojens'),
       ('Syddanmark', 'Haderslev Kommune', 6510, 'Gram'),
       ('Syddanmark', 'Haderslev Kommune', 6520, 'Toftlund'),
       ('Syddanmark', 'Haderslev Kommune', 6534, 'Agerskov'),
       ('Syddanmark', 'Haderslev Kommune', 6541, 'Bevtoft'),
       ('Syddanmark', 'Haderslev Kommune', 6560, 'Sommersted'),
       ('Syddanmark', 'Haderslev Kommune', 6630, 'Rødding'),
       ('Syddanmark', 'Billund Kommune', 6623, 'Vorbasse'),
       ('Syddanmark', 'Billund Kommune', 6682, 'Hovborg'),
       ('Syddanmark', 'Billund Kommune', 6823, 'Ansager'),
       ('Syddanmark', 'Billund Kommune', 7190, 'Billund'),
       ('Syddanmark', 'Billund Kommune', 7200, 'Grindsted'),
       ('Syddanmark', 'Billund Kommune', 7250, 'Hejnsvig'),
       ('Syddanmark', 'Billund Kommune', 7260, 'Sønder Omme'),
       ('Syddanmark', 'Billund Kommune', 7270, 'Stakroge'),
       ('Syddanmark', 'Sønderborg Kommune', 6300, 'Gråsten'),
       ('Syddanmark', 'Sønderborg Kommune', 6310, 'Broager'),
       ('Syddanmark', 'Sønderborg Kommune', 6320, 'Egernsund'),
       ('Syddanmark', 'Sønderborg Kommune', 6400, 'Sønderborg'),
       ('Syddanmark', 'Sønderborg Kommune', 6430, 'Nordborg'),
       ('Syddanmark', 'Sønderborg Kommune', 6440, 'Augustenborg'),
       ('Syddanmark', 'Sønderborg Kommune', 6470, 'Sydals'),
       ('Syddanmark', 'Tønder Kommune', 6240, 'Løgumkloster'),
       ('Syddanmark', 'Tønder Kommune', 6261, 'Bredebro'),
       ('Syddanmark', 'Tønder Kommune', 6270, 'Tønder'),
       ('Syddanmark', 'Tønder Kommune', 6280, 'Højer'),
       ('Syddanmark', 'Tønder Kommune', 6520, 'Toftlund'),
       ('Syddanmark', 'Tønder Kommune', 6534, 'Agerskov'),
       ('Syddanmark', 'Tønder Kommune', 6535, 'Branderup J'),
       ('Syddanmark', 'Tønder Kommune', 6541, 'Bevtoft'),
       ('Syddanmark', 'Tønder Kommune', 6780, 'Skærbæk'),
       ('Syddanmark', 'Tønder Kommune', 6792, 'Rømø'),
       ('Syddanmark', 'Esbjerg Kommune', 6670, 'Holsted'),
       ('Syddanmark', 'Esbjerg Kommune', 6683, 'Føvling'),
       ('Syddanmark', 'Esbjerg Kommune', 6690, 'Gørding'),
       ('Syddanmark', 'Esbjerg Kommune', 6700, 'Esbjerg'),
       ('Syddanmark', 'Esbjerg Kommune', 6705, 'Esbjerg Ø'),
       ('Syddanmark', 'Esbjerg Kommune', 6710, 'Esbjerg V'),
       ('Syddanmark', 'Esbjerg Kommune', 6715, 'Esbjerg N'),
       ('Syddanmark', 'Esbjerg Kommune', 6731, 'Tjæreborg'),
       ('Syddanmark', 'Esbjerg Kommune', 6740, 'Bramming'),
       ('Syddanmark', 'Esbjerg Kommune', 6760, 'Ribe'),
       ('Syddanmark', 'Esbjerg Kommune', 6771, 'Gredstedbro'),
       ('Syddanmark', 'Esbjerg Kommune', 6818, 'Årre'),
       ('Syddanmark', 'Fanø Kommune', 6720, 'Fanø'),
       ('Syddanmark', 'Varde Kommune', 6682, 'Hovborg'),
       ('Syddanmark', 'Varde Kommune', 6753, 'Agerbæk'),
       ('Syddanmark', 'Varde Kommune', 6800, 'Varde'),
       ('Syddanmark', 'Varde Kommune', 6818, 'Årre'),
       ('Syddanmark', 'Varde Kommune', 6823, 'Ansager'),
       ('Syddanmark', 'Varde Kommune', 6830, 'Nørre Nebel'),
       ('Syddanmark', 'Varde Kommune', 6840, 'Oksbøl'),
       ('Syddanmark', 'Varde Kommune', 6851, 'Janderup Vestj'),
       ('Syddanmark', 'Varde Kommune', 6852, 'Billum'),
       ('Syddanmark', 'Varde Kommune', 6853, 'Vejers Strand'),
       ('Syddanmark', 'Varde Kommune', 6854, 'Henne'),
       ('Syddanmark', 'Varde Kommune', 6855, 'Outrup'),
       ('Syddanmark', 'Varde Kommune', 6857, 'Blåvand'),
       ('Syddanmark', 'Varde Kommune', 6862, 'Tistrup'),
       ('Syddanmark', 'Varde Kommune', 6870, 'Ølgod'),
       ('Syddanmark', 'Varde Kommune', 6880, 'Tarm'),
       ('Syddanmark', 'Varde Kommune', 7200, 'Grindsted'),
       ('Syddanmark', 'Vejen Kommune', 6600, 'Vejen'),
       ('Syddanmark', 'Vejen Kommune', 6621, 'Gesten'),
       ('Syddanmark', 'Vejen Kommune', 6622, 'Bække'),
       ('Syddanmark', 'Vejen Kommune', 6623, 'Vorbasse'),
       ('Syddanmark', 'Vejen Kommune', 6630, 'Rødding'),
       ('Syddanmark', 'Vejen Kommune', 6650, 'Brørup'),
       ('Syddanmark', 'Vejen Kommune', 6660, 'Lintrup'),
       ('Syddanmark', 'Vejen Kommune', 6670, 'Holsted'),
       ('Syddanmark', 'Vejen Kommune', 6682, 'Hovborg'),
       ('Syddanmark', 'Vejen Kommune', 6683, 'Føvling'),
       ('Syddanmark', 'Vejen Kommune', 6690, 'Gørding'),
       ('Syddanmark', 'Vejen Kommune', 6752, 'Glejbjerg'),
       ('Syddanmark', 'Vejen Kommune', 6753, 'Agerbæk'),
       ('Syddanmark', 'Aabenraa Kommune', 6200, 'Aabenraa'),
       ('Syddanmark', 'Aabenraa Kommune', 6230, 'Rødekro'),
       ('Syddanmark', 'Aabenraa Kommune', 6330, 'Padborg'),
       ('Syddanmark', 'Aabenraa Kommune', 6340, 'Kruså'),
       ('Syddanmark', 'Aabenraa Kommune', 6360, 'Tinglev'),
       ('Syddanmark', 'Aabenraa Kommune', 6372, 'Bylderup-Bov'),
       ('Syddanmark', 'Aabenraa Kommune', 6392, 'Bolderslev'),
       ('Syddanmark', 'Aabenraa Kommune', 6534, 'Agerskov'),
       ('Syddanmark', 'Fredericia Kommune', 7000, 'Fredericia'),
       ('Syddanmark', 'Fredericia Kommune', 7007, 'Fredericia'),
       ('Syddanmark', 'Kolding Kommune', 6000, 'Kolding'),
       ('Syddanmark', 'Kolding Kommune', 6040, 'Egtved'),
       ('Syddanmark', 'Kolding Kommune', 6051, 'Almind'),
       ('Syddanmark', 'Kolding Kommune', 6052, 'Viuf'),
       ('Syddanmark', 'Kolding Kommune', 6064, 'Jordrup'),
       ('Syddanmark', 'Kolding Kommune', 6070, 'Christiansfeld'),
       ('Syddanmark', 'Kolding Kommune', 6091, 'Bjert'),
       ('Syddanmark', 'Kolding Kommune', 6092, 'Sønder Stenderup'),
       ('Syddanmark', 'Kolding Kommune', 6093, 'Sjølund'),
       ('Syddanmark', 'Kolding Kommune', 6094, 'Hejls'),
       ('Syddanmark', 'Kolding Kommune', 6100, 'Haderslev'),
       ('Syddanmark', 'Kolding Kommune', 6430, 'Nordborg'),
       ('Syddanmark', 'Kolding Kommune', 6560, 'Sommersted'),
       ('Syddanmark', 'Kolding Kommune', 6580, 'Vamdrup'),
       ('Syddanmark', 'Kolding Kommune', 6640, 'Lunderskov'),
       ('Syddanmark', 'Vejle Kommune', 6040, 'Egtved'),
       ('Syddanmark', 'Vejle Kommune', 6052, 'Viuf'),
       ('Syddanmark', 'Vejle Kommune', 6623, 'Vorbasse'),
       ('Syddanmark', 'Vejle Kommune', 7000, 'Fredericia'),
       ('Syddanmark', 'Vejle Kommune', 7080, 'Børkop'),
       ('Syddanmark', 'Vejle Kommune', 7100, 'Vejle'),
       ('Syddanmark', 'Vejle Kommune', 7120, 'Vejle Øst'),
       ('Syddanmark', 'Vejle Kommune', 7160, 'Tørring'),
       ('Syddanmark', 'Vejle Kommune', 7173, 'Vonge'),
       ('Syddanmark', 'Vejle Kommune', 7182, 'Bredsten'),
       ('Syddanmark', 'Vejle Kommune', 7183, 'Randbøl'),
       ('Syddanmark', 'Vejle Kommune', 7184, 'Vandel'),
       ('Syddanmark', 'Vejle Kommune', 7190, 'Billund'),
       ('Syddanmark', 'Vejle Kommune', 7200, 'Grindsted'),
       ('Syddanmark', 'Vejle Kommune', 7300, 'Jelling'),
       ('Syddanmark', 'Vejle Kommune', 7321, 'Gadbjerg'),
       ('Syddanmark', 'Vejle Kommune', 7323, 'Give'),
       ('Syddanmark', 'Vejle Kommune', 7330, 'Brande'),
       ('Syddanmark', 'Vejle Kommune', 7361, 'Ejstrupholm'),
       ('Hovedstaden', 'Københavns Kommune', 900, 'København C'),
       ('Hovedstaden', 'Københavns Kommune', 960, 'Udland'),
       ('Hovedstaden', 'Københavns Kommune', 999, 'København C'),
       ('Hovedstaden', 'Københavns Kommune', 1000, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1050, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1051, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1052, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1053, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1054, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1055, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1056, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1057, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1058, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1059, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1060, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1061, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1062, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1063, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1064, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1065, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1066, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1067, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1068, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1069, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1070, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1071, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1072, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1073, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1074, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1092, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1093, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1095, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1098, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1100, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1101, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1102, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1103, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1104, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1105, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1106, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1107, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1110, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1111, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1112, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1113, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1114, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1115, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1116, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1117, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1118, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1119, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1120, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1121, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1122, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1123, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1124, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1125, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1126, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1127, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1128, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1129, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1130, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1131, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1140, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1147, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1148, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1150, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1151, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1152, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1153, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1154, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1155, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1156, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1157, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1158, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1159, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1160, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1161, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1162, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1164, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1165, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1166, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1167, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1168, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1169, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1170, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1171, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1172, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1173, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1174, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1175, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1200, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1201, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1202, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1203, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1204, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1205, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1206, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1207, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1208, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1209, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1210, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1211, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1213, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1214, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1215, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1216, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1217, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1218, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1219, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1220, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1221, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1240, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1250, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1251, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1252, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1253, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1254, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1255, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1256, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1257, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1259, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1260, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1261, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1263, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1264, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1265, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1266, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1267, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1268, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1270, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1271, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1291, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1300, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1301, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1302, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1303, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1304, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1306, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1307, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1308, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1309, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1310, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1311, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1312, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1313, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1314, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1315, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1316, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1317, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1318, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1319, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1320, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1321, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1322, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1323, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1324, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1325, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1326, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1327, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1328, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1329, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1350, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1352, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1353, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1354, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1355, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1356, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1357, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1358, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1359, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1360, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1361, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1362, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1363, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1364, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1365, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1366, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1367, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1368, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1369, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1370, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1371, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1400, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1401, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1402, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1403, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1406, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1407, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1408, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1409, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1410, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1411, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1412, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1413, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1414, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1415, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1416, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1417, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1418, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1419, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1420, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1421, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1422, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1423, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1424, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1425, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1426, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1427, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1428, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1429, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1430, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1431, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1432, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1433, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1434, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1435, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1436, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1437, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1438, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1439, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1440, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1441, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1448, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1450, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1451, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1452, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1453, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1454, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1455, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1456, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1457, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1458, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1459, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1460, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1462, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1463, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1464, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1466, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1467, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1468, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1470, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1471, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1472, 'København K'),
       ('Hovedstaden', 'Københavns Kommune', 1500, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1550, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1551, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1552, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1553, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1554, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1555, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1556, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1557, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1558, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1559, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1560, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1561, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1562, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1563, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1564, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1566, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1567, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1568, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1569, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1570, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1571, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1572, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1573, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1574, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1575, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1576, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1577, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1592, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1599, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1600, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1601, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1602, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1603, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1604, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1606, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1607, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1608, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1609, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1610, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1611, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1612, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1613, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1614, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1615, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1616, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1617, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1618, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1619, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1620, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1621, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1622, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1623, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1624, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1630, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1631, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1632, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1633, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1634, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1635, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1650, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1651, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1652, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1653, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1654, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1655, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1656, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1657, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1658, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1659, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1660, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1661, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1662, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1663, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1664, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1665, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1666, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1667, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1668, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1669, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1670, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1671, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1672, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1673, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1674, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1675, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1676, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1677, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1699, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1700, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1701, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1702, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1703, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1704, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1705, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1706, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1707, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1708, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1709, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1710, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1711, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1712, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1714, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1715, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1716, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1717, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1718, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1719, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1720, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1721, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1722, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1723, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1724, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1725, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1726, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1727, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1728, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1729, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1730, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1731, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1732, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1733, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1734, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1735, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1736, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1737, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1738, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1739, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1749, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1750, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1751, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1752, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1753, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1754, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1755, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1756, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1757, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1758, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1759, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1760, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1761, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1762, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1763, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1764, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1765, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1766, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1770, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1771, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1772, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1773, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1774, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1775, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1777, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1780, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1785, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1786, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1787, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1790, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1799, 'København V'),
       ('Hovedstaden', 'Københavns Kommune', 1810, 'Frederiksberg C'),
       ('Hovedstaden', 'Københavns Kommune', 2000, 'Frederiksberg'),
       ('Hovedstaden', 'Københavns Kommune', 2100, 'København Ø'),
       ('Hovedstaden', 'Københavns Kommune', 2150, 'Nordhavn'),
       ('Hovedstaden', 'Københavns Kommune', 2200, 'København N'),
       ('Hovedstaden', 'Københavns Kommune', 2300, 'København S'),
       ('Hovedstaden', 'Københavns Kommune', 2400, 'København NV'),
       ('Hovedstaden', 'Københavns Kommune', 2450, 'København SV'),
       ('Hovedstaden', 'Københavns Kommune', 2500, 'Valby'),
       ('Hovedstaden', 'Københavns Kommune', 2610, 'Rødovre'),
       ('Hovedstaden', 'Københavns Kommune', 2700, 'Brønshøj'),
       ('Hovedstaden', 'Københavns Kommune', 2720, 'Vanløse'),
       ('Hovedstaden', 'Københavns Kommune', 2770, 'Kastrup'),
       ('Hovedstaden', 'Københavns Kommune', 2860, 'Søborg'),
       ('Hovedstaden', 'Københavns Kommune', 2900, 'Hellerup'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1800, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1801, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1802, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1803, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1804, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1805, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1806, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1807, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1808, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1809, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1810, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1811, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1812, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1813, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1814, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1815, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1816, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1817, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1818, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1819, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1820, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1822, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1823, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1824, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1825, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1826, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1827, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1828, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1829, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1850, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1851, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1852, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1853, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1854, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1855, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1856, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1857, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1860, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1861, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1862, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1863, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1864, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1865, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1866, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1867, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1868, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1870, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1871, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1872, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1873, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1874, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1875, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1876, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1877, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1878, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1879, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1900, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1901, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1902, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1903, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1904, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1905, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1906, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1908, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1909, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1910, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1911, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1912, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1913, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1914, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1915, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1916, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1917, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1920, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1921, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1922, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1923, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1924, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1925, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1926, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1927, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1928, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1950, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1951, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1952, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1953, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1954, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1955, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1956, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1957, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1958, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1959, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1960, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1961, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1962, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1963, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1964, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1965, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1966, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1967, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1970, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1971, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1972, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1973, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 1974, 'Frederiksberg C'),
       ('Hovedstaden', 'Frederiksberg Kommune', 2000, 'Frederiksberg'),
       ('Hovedstaden', 'Frederiksberg Kommune', 2200, 'København N'),
       ('Hovedstaden', 'Frederiksberg Kommune', 2500, 'Valby'),
       ('Hovedstaden', 'Frederiksberg Kommune', 2720, 'Vanløse'),
       ('Hovedstaden', 'Ballerup Kommune', 2730, 'Herlev'),
       ('Hovedstaden', 'Ballerup Kommune', 2740, 'Skovlunde'),
       ('Hovedstaden', 'Ballerup Kommune', 2750, 'Ballerup'),
       ('Hovedstaden', 'Ballerup Kommune', 2760, 'Måløv'),
       ('Hovedstaden', 'Ballerup Kommune', 3500, 'Værløse'),
       ('Hovedstaden', 'Brøndby Kommune', 917, 'Københavns Pakkecent'),
       ('Hovedstaden', 'Brøndby Kommune', 2600, 'Glostrup'),
       ('Hovedstaden', 'Brøndby Kommune', 2605, 'Brøndby'),
       ('Hovedstaden', 'Brøndby Kommune', 2620, 'Albertslund'),
       ('Hovedstaden', 'Brøndby Kommune', 2650, 'Hvidovre'),
       ('Hovedstaden', 'Brøndby Kommune', 2660, 'Brøndby Strand'),
       ('Hovedstaden', 'Dragør Kommune', 2791, 'Dragør'),
       ('Hovedstaden', 'Gentofte Kommune', 2800, 'Kongens Lyngby'),
       ('Hovedstaden', 'Gentofte Kommune', 2820, 'Gentofte'),
       ('Hovedstaden', 'Gentofte Kommune', 2870, 'Dyssegård'),
       ('Hovedstaden', 'Gentofte Kommune', 2900, 'Hellerup'),
       ('Hovedstaden', 'Gentofte Kommune', 2920, 'Charlottenlund'),
       ('Hovedstaden', 'Gentofte Kommune', 2930, 'Klampenborg'),
       ('Hovedstaden', 'Gladsaxe Kommune', 2730, 'Herlev'),
       ('Hovedstaden', 'Gladsaxe Kommune', 2800, 'Kongens Lyngby'),
       ('Hovedstaden', 'Gladsaxe Kommune', 2820, 'Gentofte'),
       ('Hovedstaden', 'Gladsaxe Kommune', 2860, 'Søborg'),
       ('Hovedstaden', 'Gladsaxe Kommune', 2880, 'Bagsværd'),
       ('Hovedstaden', 'Gladsaxe Kommune', 3500, 'Værløse'),
       ('Hovedstaden', 'Glostrup Kommune', 2600, 'Glostrup'),
       ('Hovedstaden', 'Herlev Kommune', 2730, 'Herlev'),
       ('Hovedstaden', 'Herlev Kommune', 2740, 'Skovlunde'),
       ('Hovedstaden', 'Herlev Kommune', 2880, 'Bagsværd'),
       ('Hovedstaden', 'Albertslund Kommune', 2600, 'Glostrup'),
       ('Hovedstaden', 'Albertslund Kommune', 2620, 'Albertslund'),
       ('Hovedstaden', 'Albertslund Kommune', 2750, 'Ballerup'),
       ('Hovedstaden', 'Hvidovre Kommune', 2610, 'Rødovre'),
       ('Hovedstaden', 'Hvidovre Kommune', 2650, 'Hvidovre'),
       ('Hovedstaden', 'Hvidovre Kommune', 2660, 'Brøndby Strand'),
       ('Hovedstaden', 'Høje-Taastrup Kommune', 800, 'Høje Taastrup'),
       ('Hovedstaden', 'Høje-Taastrup Kommune', 2630, 'Taastrup'),
       ('Hovedstaden', 'Høje-Taastrup Kommune', 2640, 'Hedehusene'),
       ('Hovedstaden', 'Høje-Taastrup Kommune', 4000, 'Roskilde'),
       ('Hovedstaden', 'Lyngby-Taarbæk Kommune', 2800, 'Kongens Lyngby'),
       ('Hovedstaden', 'Lyngby-Taarbæk Kommune', 2830, 'Virum'),
       ('Hovedstaden', 'Lyngby-Taarbæk Kommune', 2840, 'Holte'),
       ('Hovedstaden', 'Lyngby-Taarbæk Kommune', 2930, 'Klampenborg'),
       ('Hovedstaden', 'Lyngby-Taarbæk Kommune', 3500, 'Værløse'),
       ('Hovedstaden', 'Rødovre Kommune', 2610, 'Rødovre'),
       ('Hovedstaden', 'Rødovre Kommune', 2730, 'Herlev'),
       ('Hovedstaden', 'Ishøj Kommune', 2635, 'Ishøj'),
       ('Hovedstaden', 'Ishøj Kommune', 2640, 'Hedehusene'),
       ('Hovedstaden', 'Tårnby Kommune', 1532, 'København V'),
       ('Hovedstaden', 'Tårnby Kommune', 1533, 'København V'),
       ('Hovedstaden', 'Tårnby Kommune', 2300, 'København S'),
       ('Hovedstaden', 'Tårnby Kommune', 2770, 'Kastrup'),
       ('Hovedstaden', 'Tårnby Kommune', 2791, 'Dragør'),
       ('Hovedstaden', 'Vallensbæk Kommune', 2625, 'Vallensbæk'),
       ('Hovedstaden', 'Vallensbæk Kommune', 2665, 'Vallensbæk Strand'),
       ('Hovedstaden', 'Furesø Kommune', 2880, 'Bagsværd'),
       ('Hovedstaden', 'Furesø Kommune', 3460, 'Birkerød'),
       ('Hovedstaden', 'Furesø Kommune', 3500, 'Værløse'),
       ('Hovedstaden', 'Furesø Kommune', 3520, 'Farum'),
       ('Hovedstaden', 'Furesø Kommune', 3540, 'Lynge'),
       ('Hovedstaden', 'Allerød Kommune', 3400, 'Hillerød'),
       ('Hovedstaden', 'Allerød Kommune', 3450, 'Allerød'),
       ('Hovedstaden', 'Allerød Kommune', 3460, 'Birkerød'),
       ('Hovedstaden', 'Allerød Kommune', 3520, 'Farum'),
       ('Hovedstaden', 'Allerød Kommune', 3540, 'Lynge'),
       ('Hovedstaden', 'Allerød Kommune', 3550, 'Slangerup'),
       ('Hovedstaden', 'Fredensborg Kommune', 2970, 'Hørsholm'),
       ('Hovedstaden', 'Fredensborg Kommune', 2980, 'Kokkedal'),
       ('Hovedstaden', 'Fredensborg Kommune', 2990, 'Nivå'),
       ('Hovedstaden', 'Fredensborg Kommune', 3050, 'Humlebæk'),
       ('Hovedstaden', 'Fredensborg Kommune', 3060, 'Espergærde'),
       ('Hovedstaden', 'Fredensborg Kommune', 3400, 'Hillerød'),
       ('Hovedstaden', 'Fredensborg Kommune', 3450, 'Allerød'),
       ('Hovedstaden', 'Fredensborg Kommune', 3480, 'Fredensborg'),
       ('Hovedstaden', 'Fredensborg Kommune', 3490, 'Kvistgård'),
       ('Hovedstaden', 'Helsingør Kommune', 3000, 'Helsingør'),
       ('Hovedstaden', 'Helsingør Kommune', 3050, 'Humlebæk'),
       ('Hovedstaden', 'Helsingør Kommune', 3060, 'Espergærde'),
       ('Hovedstaden', 'Helsingør Kommune', 3070, 'Snekkersten'),
       ('Hovedstaden', 'Helsingør Kommune', 3080, 'Tikøb'),
       ('Hovedstaden', 'Helsingør Kommune', 3100, 'Hornbæk'),
       ('Hovedstaden', 'Helsingør Kommune', 3140, 'Ålsgårde'),
       ('Hovedstaden', 'Helsingør Kommune', 3150, 'Hellebæk'),
       ('Hovedstaden', 'Helsingør Kommune', 3230, 'Græsted'),
       ('Hovedstaden', 'Helsingør Kommune', 3480, 'Fredensborg'),
       ('Hovedstaden', 'Helsingør Kommune', 3490, 'Kvistgård'),
       ('Hovedstaden', 'Hillerød Kommune', 3200, 'Helsinge'),
       ('Hovedstaden', 'Hillerød Kommune', 3230, 'Græsted'),
       ('Hovedstaden', 'Hillerød Kommune', 3310, 'Ølsted'),
       ('Hovedstaden', 'Hillerød Kommune', 3320, 'Skævinge'),
       ('Hovedstaden', 'Hillerød Kommune', 3330, 'Gørløse'),
       ('Hovedstaden', 'Hillerød Kommune', 3400, 'Hillerød'),
       ('Hovedstaden', 'Hillerød Kommune', 3450, 'Allerød'),
       ('Hovedstaden', 'Hillerød Kommune', 3480, 'Fredensborg'),
       ('Hovedstaden', 'Hillerød Kommune', 3540, 'Lynge'),
       ('Hovedstaden', 'Hillerød Kommune', 3550, 'Slangerup'),
       ('Hovedstaden', 'Hillerød Kommune', 3600, 'Frederikssund'),
       ('Hovedstaden', 'Hørsholm Kommune', 2950, 'Vedbæk'),
       ('Hovedstaden', 'Hørsholm Kommune', 2960, 'Rungsted Kyst'),
       ('Hovedstaden', 'Hørsholm Kommune', 2970, 'Hørsholm'),
       ('Hovedstaden', 'Hørsholm Kommune', 2980, 'Kokkedal'),
       ('Hovedstaden', 'Rudersdal Kommune', 2800, 'Kongens Lyngby'),
       ('Hovedstaden', 'Rudersdal Kommune', 2830, 'Virum'),
       ('Hovedstaden', 'Rudersdal Kommune', 2840, 'Holte'),
       ('Hovedstaden', 'Rudersdal Kommune', 2850, 'Nærum'),
       ('Hovedstaden', 'Rudersdal Kommune', 2942, 'Skodsborg'),
       ('Hovedstaden', 'Rudersdal Kommune', 2950, 'Vedbæk'),
       ('Hovedstaden', 'Rudersdal Kommune', 2970, 'Hørsholm'),
       ('Hovedstaden', 'Rudersdal Kommune', 3460, 'Birkerød'),
       ('Hovedstaden', 'Egedal Kommune', 2750, 'Ballerup'),
       ('Hovedstaden', 'Egedal Kommune', 2765, 'Smørum'),
       ('Hovedstaden', 'Egedal Kommune', 3500, 'Værløse'),
       ('Hovedstaden', 'Egedal Kommune', 3520, 'Farum'),
       ('Hovedstaden', 'Egedal Kommune', 3540, 'Lynge'),
       ('Hovedstaden', 'Egedal Kommune', 3550, 'Slangerup'),
       ('Hovedstaden', 'Egedal Kommune', 3650, 'Ølstykke'),
       ('Hovedstaden', 'Egedal Kommune', 3660, 'Stenløse'),
       ('Hovedstaden', 'Egedal Kommune', 3670, 'Veksø Sjælland'),
       ('Hovedstaden', 'Frederikssund Kommune', 3550, 'Slangerup'),
       ('Hovedstaden', 'Frederikssund Kommune', 3600, 'Frederikssund'),
       ('Hovedstaden', 'Frederikssund Kommune', 3630, 'Jægerspris'),
       ('Hovedstaden', 'Frederikssund Kommune', 4050, 'Skibby'),
       ('Hovedstaden', 'Halsnæs Kommune', 3300, 'Frederiksværk'),
       ('Hovedstaden', 'Halsnæs Kommune', 3310, 'Ølsted'),
       ('Hovedstaden', 'Halsnæs Kommune', 3320, 'Skævinge'),
       ('Hovedstaden', 'Halsnæs Kommune', 3360, 'Liseleje'),
       ('Hovedstaden', 'Halsnæs Kommune', 3370, 'Melby'),
       ('Hovedstaden', 'Halsnæs Kommune', 3390, 'Hundested'),
       ('Hovedstaden', 'Halsnæs Kommune', 3600, 'Frederikssund'),
       ('Hovedstaden', 'Gribskov Kommune', 3100, 'Hornbæk'),
       ('Hovedstaden', 'Gribskov Kommune', 3120, 'Dronningmølle'),
       ('Hovedstaden', 'Gribskov Kommune', 3200, 'Helsinge'),
       ('Hovedstaden', 'Gribskov Kommune', 3210, 'Vejby'),
       ('Hovedstaden', 'Gribskov Kommune', 3220, 'Tisvildeleje'),
       ('Hovedstaden', 'Gribskov Kommune', 3230, 'Græsted'),
       ('Hovedstaden', 'Gribskov Kommune', 3250, 'Gilleleje'),
       ('Hovedstaden', 'Gribskov Kommune', 3300, 'Frederiksværk'),
       ('Hovedstaden', 'Bornholm Kommune', 3700, 'Rønne'),
       ('Hovedstaden', 'Bornholm Kommune', 3720, 'Aakirkeby'),
       ('Hovedstaden', 'Bornholm Kommune', 3730, 'Nexø'),
       ('Hovedstaden', 'Bornholm Kommune', 3740, 'Svaneke'),
       ('Hovedstaden', 'Bornholm Kommune', 3751, 'Østermarie'),
       ('Hovedstaden', 'Bornholm Kommune', 3760, 'Gudhjem'),
       ('Hovedstaden', 'Bornholm Kommune', 3770, 'Allinge'),
       ('Hovedstaden', 'Bornholm Kommune', 3782, 'Klemensker'),
       ('Hovedstaden', 'Bornholm Kommune', 3790, 'Hasle'),
       ('Hovedstaden', 'Christiansø', 3760, 'Gudhjem'),
       ('Sjælland', 'Greve Kommune', 2640, 'Hedehusene'),
       ('Sjælland', 'Greve Kommune', 2670, 'Greve'),
       ('Sjælland', 'Greve Kommune', 2690, 'Karlslunde'),
       ('Sjælland', 'Greve Kommune', 4030, 'Tune'),
       ('Sjælland', 'Køge Kommune', 4100, 'Ringsted'),
       ('Sjælland', 'Køge Kommune', 4130, 'Viby Sjælland'),
       ('Sjælland', 'Køge Kommune', 4140, 'Borup'),
       ('Sjælland', 'Køge Kommune', 4174, 'Jystrup Midtsj'),
       ('Sjælland', 'Køge Kommune', 4320, 'Lejre'),
       ('Sjælland', 'Køge Kommune', 4600, 'Køge'),
       ('Sjælland', 'Køge Kommune', 4623, 'Lille Skensved'),
       ('Sjælland', 'Køge Kommune', 4632, 'Bjæverskov'),
       ('Sjælland', 'Køge Kommune', 4681, 'Herfølge'),
       ('Sjælland', 'Køge Kommune', 4682, 'Tureby'),
       ('Sjælland', 'Roskilde Kommune', 2640, 'Hedehusene'),
       ('Sjælland', 'Roskilde Kommune', 3670, 'Veksø Sjælland'),
       ('Sjælland', 'Roskilde Kommune', 4000, 'Roskilde'),
       ('Sjælland', 'Roskilde Kommune', 4030, 'Tune'),
       ('Sjælland', 'Roskilde Kommune', 4040, 'Jyllinge'),
       ('Sjælland', 'Roskilde Kommune', 4130, 'Viby Sjælland'),
       ('Sjælland', 'Roskilde Kommune', 4140, 'Borup'),
       ('Sjælland', 'Roskilde Kommune', 4320, 'Lejre'),
       ('Sjælland', 'Roskilde Kommune', 4621, 'Gadstrup'),
       ('Sjælland', 'Roskilde Kommune', 4622, 'Havdrup'),
       ('Sjælland', 'Roskilde Kommune', 4623, 'Lille Skensved'),
       ('Sjælland', 'Solrød Kommune', 2680, 'Solrød Strand'),
       ('Sjælland', 'Solrød Kommune', 2690, 'Karlslunde'),
       ('Sjælland', 'Solrød Kommune', 4622, 'Havdrup'),
       ('Sjælland', 'Solrød Kommune', 4623, 'Lille Skensved'),
       ('Sjælland', 'Odsherred Kommune', 4500, 'Nykøbing Sj'),
       ('Sjælland', 'Odsherred Kommune', 4534, 'Hørve'),
       ('Sjælland', 'Odsherred Kommune', 4540, 'Fårevejle'),
       ('Sjælland', 'Odsherred Kommune', 4550, 'Asnæs'),
       ('Sjælland', 'Odsherred Kommune', 4560, 'Vig'),
       ('Sjælland', 'Odsherred Kommune', 4571, 'Grevinge'),
       ('Sjælland', 'Odsherred Kommune', 4572, 'Nørre Asmindrup'),
       ('Sjælland', 'Odsherred Kommune', 4573, 'Højby'),
       ('Sjælland', 'Odsherred Kommune', 4581, 'Rørvig'),
       ('Sjælland', 'Odsherred Kommune', 4583, 'Sjællands Odde'),
       ('Sjælland', 'Odsherred Kommune', 4591, 'Føllenslev'),
       ('Sjælland', 'Holbæk Kommune', 4100, 'Ringsted'),
       ('Sjælland', 'Holbæk Kommune', 4295, 'Stenlille'),
       ('Sjælland', 'Holbæk Kommune', 4296, 'Nyrup'),
       ('Sjælland', 'Holbæk Kommune', 4300, 'Holbæk'),
       ('Sjælland', 'Holbæk Kommune', 4330, 'Hvalsø'),
       ('Sjælland', 'Holbæk Kommune', 4340, 'Tølløse'),
       ('Sjælland', 'Holbæk Kommune', 4350, 'Ugerløse'),
       ('Sjælland', 'Holbæk Kommune', 4360, 'Kirke Eskilstrup'),
       ('Sjælland', 'Holbæk Kommune', 4370, 'Store Merløse'),
       ('Sjælland', 'Holbæk Kommune', 4390, 'Vipperød'),
       ('Sjælland', 'Holbæk Kommune', 4420, 'Regstrup'),
       ('Sjælland', 'Holbæk Kommune', 4440, 'Mørkøv'),
       ('Sjælland', 'Holbæk Kommune', 4450, 'Jyderup'),
       ('Sjælland', 'Holbæk Kommune', 4460, 'Snertinge'),
       ('Sjælland', 'Holbæk Kommune', 4470, 'Svebølle'),
       ('Sjælland', 'Holbæk Kommune', 4520, 'Svinninge'),
       ('Sjælland', 'Holbæk Kommune', 4532, 'Gislinge'),
       ('Sjælland', 'Faxe Kommune', 4100, 'Ringsted'),
       ('Sjælland', 'Faxe Kommune', 4160, 'Herlufmagle'),
       ('Sjælland', 'Faxe Kommune', 4640, 'Faxe'),
       ('Sjælland', 'Faxe Kommune', 4652, 'Hårlev'),
       ('Sjælland', 'Faxe Kommune', 4653, 'Karise'),
       ('Sjælland', 'Faxe Kommune', 4654, 'Faxe Ladeplads'),
       ('Sjælland', 'Faxe Kommune', 4682, 'Tureby'),
       ('Sjælland', 'Faxe Kommune', 4683, 'Rønnede'),
       ('Sjælland', 'Faxe Kommune', 4684, 'Holmegaard'),
       ('Sjælland', 'Faxe Kommune', 4690, 'Haslev'),
       ('Sjælland', 'Faxe Kommune', 4733, 'Tappernøje'),
       ('Sjælland', 'Kalundborg Kommune', 4200, 'Slagelse'),
       ('Sjælland', 'Kalundborg Kommune', 4270, 'Høng'),
       ('Sjælland', 'Kalundborg Kommune', 4281, 'Gørlev'),
       ('Sjælland', 'Kalundborg Kommune', 4291, 'Ruds Vedby'),
       ('Sjælland', 'Kalundborg Kommune', 4293, 'Dianalund'),
       ('Sjælland', 'Kalundborg Kommune', 4400, 'Kalundborg'),
       ('Sjælland', 'Kalundborg Kommune', 4450, 'Jyderup'),
       ('Sjælland', 'Kalundborg Kommune', 4460, 'Snertinge'),
       ('Sjælland', 'Kalundborg Kommune', 4470, 'Svebølle'),
       ('Sjælland', 'Kalundborg Kommune', 4480, 'Store Fuglede'),
       ('Sjælland', 'Kalundborg Kommune', 4490, 'Jerslev Sjælland'),
       ('Sjælland', 'Kalundborg Kommune', 4534, 'Hørve'),
       ('Sjælland', 'Kalundborg Kommune', 4591, 'Føllenslev'),
       ('Sjælland', 'Kalundborg Kommune', 4592, 'Sejerø'),
       ('Sjælland', 'Kalundborg Kommune', 4593, 'Eskebjerg'),
       ('Sjælland', 'Ringsted Kommune', 4100, 'Ringsted'),
       ('Sjælland', 'Ringsted Kommune', 4140, 'Borup'),
       ('Sjælland', 'Ringsted Kommune', 4173, 'Fjenneslev'),
       ('Sjælland', 'Ringsted Kommune', 4174, 'Jystrup Midtsj'),
       ('Sjælland', 'Ringsted Kommune', 4180, 'Sorø'),
       ('Sjælland', 'Ringsted Kommune', 4330, 'Hvalsø'),
       ('Sjælland', 'Ringsted Kommune', 4360, 'Kirke Eskilstrup'),
       ('Sjælland', 'Ringsted Kommune', 4370, 'Store Merløse'),
       ('Sjælland', 'Ringsted Kommune', 4690, 'Haslev'),
       ('Sjælland', 'Slagelse Kommune', 4180, 'Sorø'),
       ('Sjælland', 'Slagelse Kommune', 4190, 'Munke Bjergby'),
       ('Sjælland', 'Slagelse Kommune', 4200, 'Slagelse'),
       ('Sjælland', 'Slagelse Kommune', 4220, 'Korsør'),
       ('Sjælland', 'Slagelse Kommune', 4230, 'Skælskør'),
       ('Sjælland', 'Slagelse Kommune', 4241, 'Vemmelev'),
       ('Sjælland', 'Slagelse Kommune', 4242, 'Boeslunde'),
       ('Sjælland', 'Slagelse Kommune', 4243, 'Rude'),
       ('Sjælland', 'Slagelse Kommune', 4250, 'Fuglebjerg'),
       ('Sjælland', 'Slagelse Kommune', 4261, 'Dalmose'),
       ('Sjælland', 'Slagelse Kommune', 4262, 'Sandved'),
       ('Sjælland', 'Slagelse Kommune', 4270, 'Høng'),
       ('Sjælland', 'Stevns Kommune', 4600, 'Køge'),
       ('Sjælland', 'Stevns Kommune', 4652, 'Hårlev'),
       ('Sjælland', 'Stevns Kommune', 4653, 'Karise'),
       ('Sjælland', 'Stevns Kommune', 4660, 'Store Heddinge'),
       ('Sjælland', 'Stevns Kommune', 4671, 'Strøby'),
       ('Sjælland', 'Stevns Kommune', 4672, 'Klippinge'),
       ('Sjælland', 'Stevns Kommune', 4673, 'Rødvig Stevns'),
       ('Sjælland', 'Stevns Kommune', 4682, 'Tureby'),
       ('Sjælland', 'Sorø Kommune', 4100, 'Ringsted'),
       ('Sjælland', 'Sorø Kommune', 4173, 'Fjenneslev'),
       ('Sjælland', 'Sorø Kommune', 4180, 'Sorø'),
       ('Sjælland', 'Sorø Kommune', 4190, 'Munke Bjergby'),
       ('Sjælland', 'Sorø Kommune', 4200, 'Slagelse'),
       ('Sjælland', 'Sorø Kommune', 4291, 'Ruds Vedby'),
       ('Sjælland', 'Sorø Kommune', 4293, 'Dianalund'),
       ('Sjælland', 'Sorø Kommune', 4295, 'Stenlille'),
       ('Sjælland', 'Sorø Kommune', 4296, 'Nyrup'),
       ('Sjælland', 'Sorø Kommune', 4370, 'Store Merløse'),
       ('Sjælland', 'Lejre Kommune', 4000, 'Roskilde'),
       ('Sjælland', 'Lejre Kommune', 4060, 'Kirke Såby'),
       ('Sjælland', 'Lejre Kommune', 4070, 'Kirke Hyllinge'),
       ('Sjælland', 'Lejre Kommune', 4320, 'Lejre'),
       ('Sjælland', 'Lejre Kommune', 4330, 'Hvalsø'),
       ('Sjælland', 'Lejre Kommune', 4340, 'Tølløse'),
       ('Sjælland', 'Lolland Kommune', 4894, 'Øster Ulslev'),
       ('Sjælland', 'Lolland Kommune', 4895, 'Errindlev'),
       ('Sjælland', 'Lolland Kommune', 4900, 'Nakskov'),
       ('Sjælland', 'Lolland Kommune', 4912, 'Harpelunde'),
       ('Sjælland', 'Lolland Kommune', 4913, 'Horslunde'),
       ('Sjælland', 'Lolland Kommune', 4920, 'Søllested'),
       ('Sjælland', 'Lolland Kommune', 4930, 'Maribo'),
       ('Sjælland', 'Lolland Kommune', 4941, 'Bandholm'),
       ('Sjælland', 'Lolland Kommune', 4943, 'Torrig L'),
       ('Sjælland', 'Lolland Kommune', 4944, 'Fejø'),
       ('Sjælland', 'Lolland Kommune', 4951, 'Nørreballe'),
       ('Sjælland', 'Lolland Kommune', 4952, 'Stokkemarke'),
       ('Sjælland', 'Lolland Kommune', 4953, 'Vesterborg'),
       ('Sjælland', 'Lolland Kommune', 4960, 'Holeby'),
       ('Sjælland', 'Lolland Kommune', 4970, 'Rødby'),
       ('Sjælland', 'Lolland Kommune', 4983, 'Dannemare'),
       ('Sjælland', 'Næstved Kommune', 4100, 'Ringsted'),
       ('Sjælland', 'Næstved Kommune', 4160, 'Herlufmagle'),
       ('Sjælland', 'Næstved Kommune', 4171, 'Glumsø'),
       ('Sjælland', 'Næstved Kommune', 4200, 'Slagelse'),
       ('Sjælland', 'Næstved Kommune', 4243, 'Rude'),
       ('Sjælland', 'Næstved Kommune', 4250, 'Fuglebjerg'),
       ('Sjælland', 'Næstved Kommune', 4261, 'Dalmose'),
       ('Sjælland', 'Næstved Kommune', 4262, 'Sandved'),
       ('Sjælland', 'Næstved Kommune', 4640, 'Faxe'),
       ('Sjælland', 'Næstved Kommune', 4683, 'Rønnede'),
       ('Sjælland', 'Næstved Kommune', 4684, 'Holmegaard'),
       ('Sjælland', 'Næstved Kommune', 4690, 'Haslev'),
       ('Sjælland', 'Næstved Kommune', 4700, 'Næstved'),
       ('Sjælland', 'Næstved Kommune', 4733, 'Tappernøje'),
       ('Sjælland', 'Næstved Kommune', 4736, 'Karrebæksminde'),
       ('Sjælland', 'Næstved Kommune', 4750, 'Lundby'),
       ('Sjælland', 'Guldborgsund Kommune', 4800, 'Nykøbing F'),
       ('Sjælland', 'Guldborgsund Kommune', 4840, 'Nørre Alslev'),
       ('Sjælland', 'Guldborgsund Kommune', 4850, 'Stubbekøbing'),
       ('Sjælland', 'Guldborgsund Kommune', 4862, 'Guldborg'),
       ('Sjælland', 'Guldborgsund Kommune', 4863, 'Eskilstrup'),
       ('Sjælland', 'Guldborgsund Kommune', 4871, 'Horbelev'),
       ('Sjælland', 'Guldborgsund Kommune', 4872, 'Idestrup'),
       ('Sjælland', 'Guldborgsund Kommune', 4873, 'Væggerløse'),
       ('Sjælland', 'Guldborgsund Kommune', 4874, 'Gedser'),
       ('Sjælland', 'Guldborgsund Kommune', 4880, 'Nysted'),
       ('Sjælland', 'Guldborgsund Kommune', 4891, 'Toreby L'),
       ('Sjælland', 'Guldborgsund Kommune', 4892, 'Kettinge'),
       ('Sjælland', 'Guldborgsund Kommune', 4894, 'Øster Ulslev'),
       ('Sjælland', 'Guldborgsund Kommune', 4930, 'Maribo'),
       ('Sjælland', 'Guldborgsund Kommune', 4990, 'Sakskøbing'),
       ('Sjælland', 'Vordingborg Kommune', 4720, 'Præstø'),
       ('Sjælland', 'Vordingborg Kommune', 4733, 'Tappernøje'),
       ('Sjælland', 'Vordingborg Kommune', 4735, 'Mern'),
       ('Sjælland', 'Vordingborg Kommune', 4750, 'Lundby'),
       ('Sjælland', 'Vordingborg Kommune', 4760, 'Vordingborg'),
       ('Sjælland', 'Vordingborg Kommune', 4771, 'Kalvehave'),
       ('Sjælland', 'Vordingborg Kommune', 4772, 'Langebæk'),
       ('Sjælland', 'Vordingborg Kommune', 4773, 'Stensved'),
       ('Sjælland', 'Vordingborg Kommune', 4780, 'Stege'),
       ('Sjælland', 'Vordingborg Kommune', 4791, 'Borre'),
       ('Sjælland', 'Vordingborg Kommune', 4792, 'Askeby'),
       ('Sjælland', 'Vordingborg Kommune', 4793, 'Bogø By');
