version: "3.7"
services:
    neo4j_db:
        image: neo4j:4.4
        hostname: neo4j
        container_name: neo4j 
        ports:
          - "7474:7474"
          - "7687:7687"
        volumes:
          - ./neo4jDB/import:/import
          - ./neo4jDB/plugins:/plugins
        environment:
          NEO4J_AUTH: none
          NEO4J_dbms_logs_debug_level: DEBUG
          NEO4J_dbms_security_procedures_unrestricted: gds.* 
          NEO4J_dbms_security_procedures_whitelist: gds.*
    
    postgres_db:
        image: postgres:14.1-alpine
        restart: always
        hostname: postgres
        container_name: postgresDB
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=Qwerty!234
          - POSTGRES_DB=food_delivery
        ports:
          - '6969:5432'
        volumes: 
          - ./postgresDB/db:/var/lib/postgresql/data
          - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    
    mongodb_db_courier:
        image: mongo
        hostname: mongodb_courier
        restart: always
        container_name: mongoDBCourier
        volumes:
            - ./MongoData:/data/db
        ports:
            - 27017:27017
          
    mongodb_db_logs:
        image: mongo
        hostname: mongodb_log
        restart: always
        container_name: mongoDBLogs
        volumes:
            - ./logs:/data/db
        ports:
            - 27021:27017
    cache:
        image: redis:6.2-alpine
        restart: always
        container_name: cache
        ports:
          - '6379:6379'
        volumes: 
          - ./cache:/data